# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     workload.user.cattle.io/workloadselector: deployment-neurallabs-db
#   name: db
#   namespace: neurallabs
# spec:
#   progressDeadlineSeconds: 600
#   replicas: 1
#   selector:
#     matchLabels:
#       workload.user.cattle.io/workloadselector: deployment-neurallabs-db
#   strategy:
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 0
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         workload.user.cattle.io/workloadselector: deployment-neurallabs-db
#     spec:
#       containers:
#         - env:
#             - name: PGDATA
#               value: /var/lib/postgresql/data/pgdata
#           image: postgres:12
#           imagePullPolicy: Always
#           name: db
#           volumeMounts:
#             - mountPath: /var/lib/postgresql/data/pgdata
#               name: app-db-data
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       schedulerName: default-scheduler
#       terminationGracePeriodSeconds: 30
#       volumes:
#         - hostPath:
#             path: /home/vinc3/pgdata
#             type: DirectoryOrCreate
#           name: app-db-data
